//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploPlantillaWPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EjemploPlantillaWPF.Resources.MainWindowResources", typeof(MainWindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clic aqui para procesar los textos tecleados.
        /// </summary>
        public static string ClicAquiParaProcesarLosTextosTecleados {
            get {
                return ResourceManager.GetString("ClicAquiParaProcesarLosTextosTecleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige la opcion:.
        /// </summary>
        public static string EligeLaOpcion {
            get {
                return ResourceManager.GetString("EligeLaOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opcion1.
        /// </summary>
        public static string opcion1 {
            get {
                return ResourceManager.GetString("opcion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opcion2.
        /// </summary>
        public static string opcion2 {
            get {
                return ResourceManager.GetString("opcion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opcion3.
        /// </summary>
        public static string opcion3 {
            get {
                return ResourceManager.GetString("opcion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teclear aquí la prueba 1:.
        /// </summary>
        public static string TeclearAquiLaPrueba1 {
            get {
                return ResourceManager.GetString("TeclearAquiLaPrueba1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teclear aquí la prueba 2:.
        /// </summary>
        public static string TeclearAquiLaPrueba2 {
            get {
                return ResourceManager.GetString("TeclearAquiLaPrueba2", resourceCulture);
            }
        }
    }
}
